const fs=require('fs'),path=require('path');
if(!fs.readFileSync('/proc/self/cgroup','utf8').includes('/eh158.slice/'))throw new Error('Run via guarded_exec');
const {chromium}=require(process.env.ENGINE_HUB_PLAYWRIGHT||'/tmp/v3-playwright/node_modules/playwright');
const root=path.resolve(__dirname,'..'),secret=JSON.parse(fs.readFileSync(path.join(root,'.local/secrets.json'),'utf8'));
const stamp=new Date().toISOString().replace(/[:.]/g,'-'),result={checks:[],screenshots:[],requests:[]};
function check(name,value){result.checks.push({name,pass:!!value});if(!value)throw new Error(name);}
(async()=>{let b;try{b=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--renderer-process-limit=2']});const users=[];
for(const name of ['admin','viewer','chat']){const context=await b.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();page.on('request',r=>{if(r.url().includes('/api/')&&!r.url().endsWith('/login'))result.requests.push({user:name,method:r.method(),path:new URL(r.url()).pathname});});page.on('pageerror',e=>result.checks.push({name:'pageerror',pass:false,error:e.message}));await page.goto('http://127.0.0.1:15800');await page.fill('#username',name);await page.fill('#password',secret.passwords[name]);await page.click('#login-form button');await page.waitForSelector('#app',{state:'visible'});await page.click('[data-tab=overview]');await page.waitForFunction(()=>document.querySelectorAll('#nodes .card').length===6);check('same_origin_'+name,new URL(page.url()).origin==='http://127.0.0.1:15800');check('role_ui_'+name,name==='viewer'?await page.locator('#composer').isHidden():await page.locator('#new-chat').isVisible());const image=stamp+'-'+name+'-guarded.png';await page.screenshot({path:path.join(root,'evidence',image),fullPage:true});result.screenshots.push(image);users.push({name,context,page});}
check('viewer_boot_no_mutations',result.requests.filter(r=>r.user==='viewer').every(r=>r.method==='GET'));
const identities=await Promise.all(users.map(async u=>u.page.evaluate(async()=>{const r=await fetch('/api/me');return(await r.json()).user.id;})));check('three_browser_cookie_identities',new Set(identities).size===3);
const denied=await users[1].page.evaluate(async()=>{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({text:'PG'})});return r.status;});check('viewer_direct_write_denied',denied===403);
for(const u of users){await u.page.click('[data-tab=assets]');await u.page.waitForFunction(()=>document.querySelector('#asset-content').textContent.includes('remote knowledge'));check('actual_remote_asset_page_'+u.name,(await u.page.locator('#asset-content').textContent()).includes('release-'));}
const mobile=users[2];await mobile.page.setViewportSize({width:390,height:844});await mobile.page.click('[data-tab=overview]');check('mobile_no_overflow',await mobile.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const image=stamp+'-mobile-guarded.png';await mobile.page.screenshot({path:path.join(root,'evidence',image),fullPage:true});result.screenshots.push(image);
result.status=result.checks.every(x=>x.pass)?'PASS':'FAIL';
}catch(e){result.status='FAIL';result.error=e.message;throw e;}finally{if(b)await b.close();const file='browser-guarded-'+stamp+'.json';fs.writeFileSync(path.join(root,'evidence',file),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,checks:result.checks.length,evidence:file,error:result.error}));}})();
