// Real Chromium contexts; never record passwords, cookies or CSRF tokens.
const fs=require('fs'),path=require('path');
if(!fs.readFileSync('/proc/self/cgroup','utf8').includes('/eh158.slice/'))throw new Error('Run via guarded_exec');
const {chromium}=require(process.env.ENGINE_HUB_PLAYWRIGHT||'/tmp/v3-playwright/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'evidence'),stamp=new Date().toISOString().replace(/[:.]/g,'-');
const secrets=JSON.parse(fs.readFileSync(path.join(root,'.local/secrets.json'),'utf8'));
const evidence={at:new Date().toISOString(),checks:[],requests:[],screenshots:[],boundary:'Actual Chromium + owned Hermes/WeKnora; deterministic answer model, separate real Luna evidence.'};
function check(name,ok,detail){evidence.checks.push({name,pass:!!ok,detail});if(!ok)throw new Error(name);}
async function api(page,url,method='GET',body){return page.evaluate(async({url,method,body})=>{const response=await fetch('/api'+url,{method,headers:{'Content-Type':'application/json',...(method==='GET'?{}:{'X-CSRF-Token':csrf})},body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,data:await response.json()};},{url,method,body});}
async function login(browser,name,viewport={width:1440,height:1000}){const ctx=await browser.newContext({viewport});const page=await ctx.newPage();page.on('request',request=>{if(request.url().includes('/api/')&&!request.url().endsWith('/login'))evidence.requests.push({actor:name,method:request.method(),path:new URL(request.url()).pathname});});page.on('pageerror',error=>{evidence.checks.push({name:'pageerror_'+name,pass:false,detail:error.message});});await page.goto('http://127.0.0.1:15800');await page.locator('#username').fill(name);await page.locator('#password').fill(secrets.passwords[name]);await page.locator('#login-form button').click();await page.locator('#app').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#conversations').children.length>0||document.querySelector('#nodes').children.length>0);return{ctx,page,name};}
async function screenshot(user,label){const filename=`${stamp}-${label}.png`;await user.page.screenshot({path:path.join(out,filename),fullPage:true});evidence.screenshots.push(filename);}
(async()=>{let browser;try{browser=await chromium.launch({headless:true,args:['--no-sandbox']});const users=await Promise.all(['admin','viewer','chat'].map(name=>login(browser,name)));const [admin,viewer,chat]=users;
check('three_origins_one_login_url',users.every(x=>new URL(x.page.url()).origin==='http://127.0.0.1:15800'));
check('three_distinct_browser_identities',new Set(await Promise.all(users.map(async x=>(await api(x.page,'/me')).data.user.id))).size===3);
check('viewer_no_bootstrap_writes',evidence.requests.filter(x=>x.actor==='viewer').every(x=>x.method==='GET'));
check('viewer_composer_absent',await viewer.page.locator('#composer').isHidden());
check('chat_admin_hidden',await chat.page.locator('#admin-nav').isHidden());
check('admin_configuration_visible',await admin.page.locator('#admin-nav').isVisible());
for(const user of users){await user.page.locator('[data-tab="overview"]').click();await user.page.waitForFunction(()=>document.querySelectorAll('#nodes .card').length===6);await screenshot(user,user.name+'-six-nodes');}
for(const user of users){await user.page.locator('[data-tab="assets"]').click();await user.page.waitForFunction(()=>document.querySelector('#asset-content').textContent.includes('remote knowledge'));await screenshot(user,user.name+'-remote-assets');}
await admin.page.locator('#admin-nav').click();await admin.page.waitForFunction(()=>document.querySelector('#config').children.length===6);await screenshot(admin,'admin-sanitized-config');
check('admin_no_plaintext_node_keys',!(await admin.page.locator('body').innerText()).includes(Object.values(secrets.nodes)[0].key));
const readonly=await api(viewer.page,'/ask','POST',{engine:'pg',text:'Viewer direct attempt'});check('viewer_direct_write_denied',readonly.status===403);
const forbidden=await api(chat.page,'/config','PATCH',{node:'node-03',enabled:false});check('chat_direct_config_denied',forbidden.status===403);
await chat.page.locator('#new-chat').click();await chat.page.locator('#engine').selectOption('pg');await chat.page.locator('#question').fill('PG browser actual node identity and remote Skill');const admission=chat.page.waitForResponse(r=>r.url().endsWith('/api/ask')&&r.request().method()==='POST');await chat.page.locator('#send').click();const answer=await(await admission).json();check('browser_ask_route',answer.run.engine==='pg'&&answer.run.node==='node-03');await chat.page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('REAL_NODE_IDENTITY'),{},{timeout:90000});await screenshot(chat,'chat-pg-real-report');
await chat.page.locator('#question').fill('追问：继续读取同一空间');const followResponse=chat.page.waitForResponse(r=>r.url().endsWith('/api/ask')&&r.request().method()==='POST');await chat.page.locator('#send').click();const follow=await(await followResponse).json();check('browser_followup_same_session_new_run',follow.conversation.id===answer.conversation.id&&follow.run.id!==answer.run.id);await chat.page.waitForFunction(()=>document.querySelectorAll('#messages .report').length===2&&Array.from(document.querySelectorAll('#messages .report')).every(e=>e.textContent.includes('REAL_NODE_IDENTITY')),{},{timeout:90000});await screenshot(chat,'chat-followup');
const mobile=await login(browser,'chat',{width:390,height:844});await mobile.page.locator('[data-tab="overview"]').click();await screenshot(mobile,'mobile-nodes');check('mobile_no_horizontal_overflow',await mobile.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mobile.page.locator('[data-tab="assets"]').click();await mobile.page.waitForFunction(()=>document.querySelector('#asset-content').textContent.includes('remote knowledge'));await screenshot(mobile,'mobile-assets');await mobile.ctx.close();
for(const user of users)await user.ctx.close();evidence.status=evidence.checks.every(c=>c.pass)?'PASS':'FAIL';
}catch(error){evidence.status='FAIL';evidence.error=error.message;throw error;}finally{if(browser)await browser.close();const filename=`browser-${stamp}.json`;fs.writeFileSync(path.join(out,filename),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({status:evidence.status,checks:evidence.checks.length,evidence:filename,error:evidence.error}));}})();
